<a href="https://colab.research.google.com/github/albanisyahrill/tugas-akhir-data-engineering/blob/main/TA_DE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python

import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

pd.options.display.max_colwidth = 200 #max display lebar dari column nya

import warnings
warnings.filterwarnings('ignore')

# Contents

*   Read the dataset (corpus)
*   Data Cleaning

# Read the Dataset
Dataset link : https://www.kaggle.com/c/medical-notes/data. /- https://www.mtsamples.com/

In [2]:
from google.colab import files
uploaded = files.upload()

Saving deaths-and-new-cases-of-hiv.csv to deaths-and-new-cases-of-hiv.csv

In [3]:
import io
df = pd.read_csv(io.StringIO(uploaded['deaths-and-new-cases-of-hiv.csv'].decode('utf-8')))
# io.StringIO, ngubah semua character yang ada di filenya menjadi string jadi data ini text-only data
# decode('utf-8') ini buat decoder kode universal untuk internasionalisasi dan mampu mengodekan seluruh set karakter Unicode
df

,Entity,Code,Year,Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number),Incidence - HIV/AIDS - Sex: Both - Age: All Ages (Number),Prevalence - HIV/AIDS - Sex: Both - Age: All Ages (Number)
0,Afghanistan,AFG,1990,34,88.0,41.8
1,Afghanistan,AFG,1991,41,104.0,49.5
2,Afghanistan,AFG,1992,48,120.0,60.9
3,Afghanistan,AFG,1993,56,127.0,70.7
4,Afghanistan,AFG,1994,63,133.0,77.1
...,...,...,...,...,...,...
6835,Zimbabwe,ZWE,2015,29162,47925.0,124519.0
6836,Zimbabwe,ZWE,2016,27141,43867.0,124293.8
6837,Zimbabwe,ZWE,2017,24846,39255.0,123927.2
6838,Zimbabwe,ZWE,2018,22106,34073.0,123415.6
6839,Zimbabwe,ZWE,2019,20722,31509.0,122709.6

In [53]:
df.columns #Check kolom-kolom yg terdapat didalam data kita

Index(['Entity', 'Code', 'Year',
       'Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)',
       'Incidence - HIV/AIDS - Sex: Both - Age: All Ages (Number)',
       'Prevalence - HIV/AIDS - Sex: Both - Age: All Ages (Number)'],
      dtype='object')

In [52]:
df.head(5) #Check head data 5 teratas

,Entity,Code,Year,Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number),Incidence - HIV/AIDS - Sex: Both - Age: All Ages (Number),Prevalence - HIV/AIDS - Sex: Both - Age: All Ages (Number)
0,Afghanistan,AFG,1990,34,88.0,41.8
1,Afghanistan,AFG,1991,41,104.0,49.5
2,Afghanistan,AFG,1992,48,120.0,60.9
3,Afghanistan,AFG,1993,56,127.0,70.7
4,Afghanistan,AFG,1994,63,133.0,77.1

In [54]:
df.shape # Check total row + column

(6840, 6)

In [58]:
# Menghapus kolom yang tidak diperlukan
data_cleaned = df.drop(['Code', 'Prevalence - HIV/AIDS - Sex: Both - Age: All Ages (Number)'], axis=1)
data_cleaned.columns

Index(['Entity', 'Year',
       'Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)',
       'Incidence - HIV/AIDS - Sex: Both - Age: All Ages (Number)'],
      dtype='object')

In [59]:
#Check apakah ada nilai yg kosong
#Jika outputnya true artinya mengandung nilai yang kosong, sebaliknya jika outputnya false artinya semua kolom terisi
data_cleaned.isnull().any()

Entity                                                       False
Year                                                         False
Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)       False
Incidence - HIV/AIDS - Sex: Both - Age: All Ages (Number)    False
dtype: bool

In [60]:
#Mendapaktan jumlah nilai yg kosong dalam setiap kolom
data_cleaned.isnull().sum()

Entity                                                       0
Year                                                         0
Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)       0
Incidence - HIV/AIDS - Sex: Both - Age: All Ages (Number)    0
dtype: int64

In [63]:
# Mengisi data kualitatif kosong dengan nilai "Unknown"
data_cleaned['Incidence - HIV/AIDS - Sex: Both - Age: All Ages (Number)'].fillna("Unknown", inplace=True)
data_cleaned.isnull().sum()

Entity                                                       0
Year                                                         0
Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)       0
Incidence - HIV/AIDS - Sex: Both - Age: All Ages (Number)    0
dtype: int64

In [83]:
# Buat peta pemetaan untuk mengelompokkan negara berdasarkan nama negara
peta_pemetaan = {
    'Australia': 'Maju', 
    'Austria': 'Maju',
    'Belgium': 'Maju',
    'Canada': 'Maju',
    'Denmark': 'Maju',
    'Finland': 'Maju',
    'France': 'Maju',
    'Germany': 'Maju',
    'Iceland': 'Maju',
    'Ireland': 'Maju',
    'Israel': 'Maju',
    'Italy': 'Maju',
    'Japan': 'Maju',
    'Luxembourg': 'Maju',
    'Netherlands': 'Maju',
    'New Zealand': 'Maju',
    'Norway': 'Maju',
    'Singapore': 'Maju',
    'South Korea': 'Maju',
    'Spain': 'Maju',
    'Sweden': 'Maju',
    'Switzerland': 'Maju',
    'United Kingdom': 'Maju',
    'United States': 'Maju',
    'Antigua and Barbuda': 'Maju',
    'Bahamas': 'Maju',
    'Barbados': 'Maju',
    'England': 'Maju',
    'European Region (WHO)': 'Maju',
    'G20': 'Maju',
    'North America (WB)': 'Maju',
    'Northern Ireland': 'Maju',
    'OECD Countries': 'Maju',
    'Puerto Rico': 'Maju',
    'Scotland': 'Maju',
    'Wales': 'Maju',
    'Western Pacific Region (WHO)': 'Maju',
    'World': 'Maju',
    'World Bank High Income': 'Maju',
    'Albania': 'Berkembang',
    'Algeria': 'Berkembang',
    'Angola': 'Berkembang',
    'Argentina': 'Berkembang',
    'Armenia': 'Berkembang',
    'Azerbaijan': 'Berkembang',
    'Bahrain': 'Berkembang',
    'Belarus': 'Berkembang',
    'Belize': 'Berkembang',
    'Benin': 'Berkembang',
    'Bhutan': 'Berkembang',
    'Bolivia': 'Berkembang',
    'Bosnia and Herzegovina': 'Berkembang',
    'Botswana': 'Berkembang',
    'Brazil': 'Berkembang',
    'Brunei': 'Berkembang',
    'Bulgaria': 'Berkembang',
    'Burkina Faso': 'Berkembang',
    'Burundi': 'Berkembang',
    'Cambodia': 'Berkembang',
    'Cameroon': 'Berkembang',
    'Cape Verde': 'Berkembang',
    'Central African Republic': 'Berkembang',
    'Chad': 'Berkembang',
    'Chile': 'Berkembang',
    'China': 'Berkembang',
    'Colombia': 'Berkembang',
    'Comoros': 'Berkembang',
    'Congo': 'Berkembang',
    'Costa Rica': 'Berkembang',
    "Cote d'Ivoire": 'Berkembang',
    'Croatia': 'Berkembang',
    'Cuba': 'Berkembang',
    'Cyprus': 'Berkembang',
    'Czechia': 'Berkembang',
    'Democratic Republic of Congo': 'Berkembang',
    'Djibouti': 'Berkembang',
    'Dominica': 'Berkembang',
    'Dominican Republic': 'Berkembang',
    'Ecuador': 'Berkembang',
    'Egypt': 'Berkembang',
    'El Salvador': 'Berkembang',
    'Equatorial Guinea': 'Berkembang',
    'Eritrea': 'Berkembang',
    'Estonia': 'Berkembang',
    'Eswatini': 'Berkembang',
    'Ethiopia': 'Berkembang',
    'Fiji': 'Berkembang',
    'Gabon': 'Berkembang',
    'Gambia': 'Berkembang',
    'Georgia': 'Berkembang',
    'Ghana': 'Berkembang',
    'Greece': 'Berkembang',
    'Grenada': 'Berkembang',
    'Guatemala': 'Berkembang',
    'Guinea': 'Berkembang',
    'Guinea-Bissau': 'Berkembang',
    'Guyana': 'Berkembang',
    'Haiti': 'Berkembang',
    'Honduras': 'Berkembang',
    'Hungary': 'Berkembang',
    'India': 'Berkembang',
    'Indonesia': 'Berkembang',
    'Iran': 'Berkembang',
    'Iraq': 'Berkembang',
    'Jamaica': 'Berkembang',
    'Jordan': 'Berkembang',
    'Kazakhstan': 'Berkembang',
    'Kenya': 'Berkembang',
    'Kiribati': 'Berkembang',
    'Kuwait': 'Berkembang',
    'Kyrgyzstan': 'Berkembang',
    'Laos': 'Berkembang',
    'Latvia': 'Berkembang',
    'Lebanon': 'Berkembang',
    'Lesotho': 'Berkembang',
    'Liberia': 'Berkembang',
    'Libya': 'Berkembang',
    'Lithuania': 'Berkembang',
    'Madagascar': 'Berkembang',
    'Malawi': 'Berkembang',
    'Malaysia': 'Berkembang',
    'Maldives': 'Berkembang',
    'Mali': 'Berkembang',
    'Malta': 'Berkembang',
    'Marshall Islands': 'Berkembang',
    'Mauritania': 'Berkembang',
    'Mauritius': 'Berkembang',
    'Mexico': 'Berkembang',
    'Micronesia (country)': 'Berkembang',
    'Moldova': 'Berkembang',
    'Mongolia': 'Berkembang',
    'Montenegro': 'Berkembang',
    'Morocco': 'Berkembang',
    'Mozambique': 'Berkembang',
    'Myanmar': 'Berkembang',
    'Namibia': 'Berkembang',
    'Nepal': 'Berkembang',
    'Nicaragua': 'Berkembang',
    'Niger': 'Berkembang',
    'Nigeria': 'Berkembang',
    'North Korea': 'Berkembang',
    'Oman': 'Berkembang',
    'Pakistan': 'Berkembang',
    'Palau': 'Berkembang',
    'Palestine': 'Berkembang',
    'Panama': 'Berkembang',
    'Papua New Guinea': 'Berkembang',
    'Paraguay': 'Berkembang',
    'Peru': 'Berkembang',
    'Philippines': 'Berkembang',
    'Poland': 'Berkembang',
    'Portugal': 'Berkembang',
    'Qatar': 'Berkembang',
    'Romania': 'Berkembang',
    'Russia': 'Berkembang',
    'Rwanda': 'Berkembang',
    'Saint Kitts and Nevis': 'Berkembang',
    'Saint Lucia': 'Berkembang',
    'Saint Vincent and the Grenadines': 'Berkembang',
    'Samoa': 'Berkembang',
    'San Marino': 'Berkembang',
    'Sao Tome and Principe': 'Berkembang',
    'Saudi Arabia': 'Berkembang',
    'Senegal': 'Berkembang',
    'Serbia': 'Berkembang',
    'Seychelles': 'Berkembang',
    'Sierra Leone': 'Berkembang',
    'Slovakia': 'Berkembang',
    'Slovenia': 'Berkembang',
    'Solomon Islands': 'Berkembang',
    'Somalia': 'Berkembang',
    'South Africa': 'Berkembang',
    'South Sudan': 'Berkembang',
    'Sri Lanka': 'Berkembang',
    'Sudan': 'Berkembang',
    'Suriname': 'Berkembang',
    'Syria': 'Berkembang',
    'Taiwan': 'Berkembang',
    'Tajikistan': 'Berkembang',
    'Tanzania': 'Berkembang',
    'Thailand': 'Berkembang',
    'Timor': 'Berkembang',
    'Togo': 'Berkembang',
    'Tonga': 'Berkembang',
    'Trinidad and Tobago': 'Berkembang',
    'Tunisia': 'Berkembang',
    'Turkey': 'Berkembang',
    'Turkmenistan': 'Berkembang',
    'Tuvalu': 'Berkembang',
    'Uganda': 'Berkembang',
    'Ukraine': 'Berkembang',
    'United Arab Emirates': 'Berkembang',
    'Uruguay': 'Berkembang',
    'Uzbekistan': 'Berkembang',
    'Vanuatu': 'Berkembang',
    'Venezuela': 'Berkembang',
    'Vietnam': 'Berkembang',
    'Yemen': 'Berkembang',
    'Zambia': 'Berkembang',
    'Zimbabwe': 'Berkembang',
    'Bangladesh': 'Berkembang',
    'East Asia & Pacific (WB)': 'Berkembang',
    'Eastern Mediterranean Region (WHO)': 'Berkembang',
    'Europe & Central Asia (WB)': 'Berkembang',
    'Latin America & Caribbean (WB)': 'Berkembang',
    'Middle East & North Africa (WB)': 'Berkembang',
    'North Macedonia': 'Berkembang',
    'Region of the Americas (WHO)': 'Berkembang',
    'South Asia (WB)': 'Berkembang',
    'South-East Asia Region (WHO)': 'Berkembang',
    'Sub-Saharan Africa (WB)': 'Berkembang',
    'World Bank Lower Middle Income': 'Berkembang',
    'World Bank Upper Middle Income': 'Berkembang',
    'Afghanistan': 'Terbelakang',
    'African Region (WHO)': 'Terbelakang',
    'American Samoa': 'Terbelakang',
    'Andorra': 'Terbelakang',
    'Bermuda': 'Terbelakang',
    'Cook Islands': 'Terbelakang',
    'Greenland': 'Terbelakang',
    'Guam': 'Terbelakang',
    'Monaco': 'Terbelakang',
    'Nauru': 'Terbelakang',
    'Niue': 'Terbelakang',
    'Northern Mariana Islands': 'Terbelakang',
    'Tokelau': 'Terbelakang',
    'United States Virgin Islands': 'Terbelakang',
    'World Bank Low Income': 'Terbelakang',
}

# Buat kolom baru yaitu "Classification" dan terapkan pemetaan
data_cleaned['Classification'] = data_cleaned['Entity'].map(peta_pemetaan)

#Mengecek apakah ada kolom yg masih kosong
#Jika outputnya true artinya mengandung nilai yang kosong, sebaliknya jika outputnya false artinya semua kolom terisi
data_cleaned.isnull().any()

Entity                                                       False
Year                                                         False
Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)       False
Incidence - HIV/AIDS - Sex: Both - Age: All Ages (Number)    False
Classification                                               False
dtype: bool

In [84]:
# Menampilkan data
data_cleaned

,Entity,Year,Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number),Incidence - HIV/AIDS - Sex: Both - Age: All Ages (Number),Classification
0,Afghanistan,1990,34,88.0,Terbelakang
1,Afghanistan,1991,41,104.0,Terbelakang
2,Afghanistan,1992,48,120.0,Terbelakang
3,Afghanistan,1993,56,127.0,Terbelakang
4,Afghanistan,1994,63,133.0,Terbelakang
...,...,...,...,...,...
6835,Zimbabwe,2015,29162,47925.0,Berkembang
6836,Zimbabwe,2016,27141,43867.0,Berkembang
6837,Zimbabwe,2017,24846,39255.0,Berkembang
6838,Zimbabwe,2018,22106,34073.0,Berkembang
6839,Zimbabwe,2019,20722,31509.0,Berkembang

In [87]:
# Menyimpan dataset setelah proses data cleaning
data_cleaned.to_csv('data-hiv-cleaned.csv', index=False)